branch-defaults:
  master:
    environment: {{APPLICATION_ENVIRONMENT}}
environment-defaults:
  {{APPLICATION_ENVIRONMENT}}:
    branch: master
    repository: null
global:
  application_name: {{APPLICATION_NAME}}
  branch: null
  default_ec2_keyname: {{KEY}}
  default_platform: {{PLATFORM}}
  default_region: {{REGION}}
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: {{ENV}}
  repository: null
  sc: git
  workspace_type: Application
